// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://velolqdaxcgldqcoclxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbG9scWRheGNnbGRxY29jbHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODIwNjcsImV4cCI6MjA2MzQ1ODA2N30.CY0QiJ48cLGSuPIwYyoyjEHxiUX1AVjmj1q-bk5lPh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);